<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MBA.EducaOn.Cadastro.Application\MBA.EducaOn.GestaoConteudo.Application.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Cadastro.Data\MBA.EducaOn.GestaoConteudo.Data.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Cadastro.Domain\MBA.EducaOn.GestaoConteudo.Domain.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Domain\MBA.EducaOn.Core.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.EventSourcing\MBA.EducaOn.EventSourcing.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.GestaoAlunos.Application\MBA.EducaOn.GestaoAlunos.Application.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.GestaoAlunos.Data\MBA.EducaOn.GestaoAlunos.Data.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.GestaoAlunos.Domain\MBA.EducaOn.GestaoAlunos.Domain.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Pagamentos.AntiCorruption\MBA.EducaOn.Pagamentos.AntiCorruption.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Pagamentos.Business\MBA.EducaOn.Pagamentos.Business.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Pagamentos.Data\MBA.EducaOn.Pagamentos.Data.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Security\MBA.EducaOn.Security.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Vendas.Application\MBA.EducaOn.Vendas.Application.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Vendas.Data\MBA.EducaOn.Vendas.Data.csproj" />
    <ProjectReference Include="..\MBA.EducaOn.Vendas.Domain\MBA.EducaOn.Vendas.Domain.csproj" />
  </ItemGroup>

</Project>
